version: '3.9'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: algosolver-playground:*