# pull official base image
FROM s403o/playground

# set working directory
#RUN mkdir /app
RUN addgroup -S test && adduser -S semo -G test
WORKDIR /app
# install app dependencies
COPY package*.json ./
RUN npm install

# add app
COPY . ./
RUN chown -R semo:test /app

# listener port at runtime
EXPOSE 3000

# start app
USER semo
CMD ["node", "index.js"]