# pull official base image
FROM alpine

# install node
RUN apk update && \
    apk add --update nodejs && \
    apk add --update g++ && \
    apk add --update npm

# set working directory
RUN mkdir -p /app
WORKDIR /app

# install app dependencies
COPY /server/package*.json ./
RUN npm install

# add app
COPY server /app

# listener port at runtime
EXPOSE 3000

# start app
CMD ["node", "index.js"]